// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/sanity.ts
import { createClient } from "npm:@sanity/client@^7.20.0";
function mcpSanityClient() {
  return createClient({
    projectId: "215aijyj",
    dataset: "production",
    apiVersion: "2024-01-01",
    useCdn: false
  });
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published TikShopTok blog posts (newest first) with title, slug, date, category, tags and excerpt.",
  inputSchema: {
    limit: z.number().int().optional().describe("How many posts to return. Defaults to 10."),
    category: z.string().optional().describe("Optional category filter: tiktok-shop, ugc, productos-virales or estrategia.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    const filter = category ? ` && category == $category` : "";
    const posts = await mcpSanityClient().fetch(
      `*[_type == "post" && defined(slug.current)${filter}] | order(publishedAt desc)[0...$take]{
        title, "slug": slug.current, publishedAt, category, tags, excerpt
      }`,
      { take, ...category ? { category } : {} }
    );
    const rows = Array.isArray(posts) ? posts : [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { posts: rows }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
function toPlainText(body) {
  if (!Array.isArray(body)) return "";
  return body.map((block) => {
    if (block._type === "table") {
      return (block.rows ?? []).map((row) => (row.cells ?? []).join(" | ")).join("\n");
    }
    const text = (block.children ?? []).map((c) => c.text ?? "").join("");
    if (block.style === "h2") return `## ${text}`;
    if (block.style === "h3") return `### ${text}`;
    if (block.style === "h4") return `#### ${text}`;
    if (block.style === "blockquote") return `> ${text}`;
    return text;
  }).filter(Boolean).join("\n\n");
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Get one TikShopTok blog post by slug, including its full body as plain text.",
  inputSchema: { slug: z2.string().trim().min(1).describe("The post slug, e.g. pulso-tiktok-shop-espana-2026-09-14.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const post = await mcpSanityClient().fetch(
      `*[_type == "post" && slug.current == $slug][0]{
        title, "slug": slug.current, publishedAt, category, tags, excerpt, body
      }`,
      { slug }
    );
    if (!post) throw new ToolError(`No blog post found with slug "${slug}".`);
    const result = { ...post, body: toPlainText(post.body), url: `https://tikshoptok.com/blog/${slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { post: result }
    };
  }
});

// src/lib/mcp/tools/search-blog-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var search_blog_posts_default = defineTool3({
  name: "search_blog_posts",
  title: "Search blog posts",
  description: "Search TikShopTok blog posts by free text across title, excerpt and tags. Returns matching posts newest first.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Search text, e.g. 'creadores UGC' or 'ranking tiendas'."),
    limit: z3.number().int().optional().describe("How many results to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    const posts = await mcpSanityClient().fetch(
      `*[_type == "post" && defined(slug.current) && (
          title match $q || excerpt match $q || $q in tags[] || count(tags[@ match $q]) > 0
       )] | order(publishedAt desc)[0...$take]{
        title, "slug": slug.current, publishedAt, category, tags, excerpt
      }`,
      { q: `*${query}*`, take }
    );
    const rows = Array.isArray(posts) ? posts : [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { results: rows, query }
    };
  }
});

// src/lib/mcp/tools/get-agency-overview.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
var overview = {
  brand: "TikShopTok",
  positioning: "Agencia nativa de TikTok Shop y social commerce: product research, creaci\xF3n de marcas, gesti\xF3n de creadores UGC y lanzamiento de productos virales.",
  services: [
    "Product research: detecci\xF3n de productos virales y validaci\xF3n de demanda en TikTok Shop.",
    "Creaci\xF3n de marcas listas para operar en TikTok Shop.",
    "Conexi\xF3n y gesti\xF3n de creadores UGC, incluidos creadores top de Espa\xF1a.",
    "Adaptaci\xF3n de la propuesta de valor de producto desde otros marketplaces a TikTok Shop."
  ],
  results: [
    "Miles de euros en facturaci\xF3n generada para marcas.",
    "M\xE1s de 5 millones de visitas en contenido con producto a la venta.",
    "M\xE1s de 30 productos seleccionados y lanzados en m\xE1s de 10 categor\xEDas.",
    "Colaboraciones con creadores top 1 de Espa\xF1a."
  ],
  links: {
    site: "https://tikshoptok.com",
    productResearch: "https://tikshoptok.com/product-research",
    blog: "https://tikshoptok.com/blog"
  }
};
var get_agency_overview_default = defineTool4({
  name: "get_agency_overview",
  title: "Get agency overview",
  description: "Get TikShopTok's positioning, services, headline results and key site links. Useful context before answering questions about the agency.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: overview
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zlklqsehcdketizzwmir";
var mcp_default = defineMcp({
  name: "tikshoptok-agency",
  title: "TikShopTok Agency",
  version: "0.1.0",
  instructions: "Herramientas de TikShopTok, agencia de TikTok Shop y social commerce. Usa get_agency_overview para el contexto de la agencia, list_blog_posts y search_blog_posts para encontrar entradas del blog (incluido el tracker diario 'Pulso TikTok Shop Espa\xF1a'), y get_blog_post para leer una entrada completa.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_agency_overview_default, list_blog_posts_default, search_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
